'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.17379
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("PrinterQueueWatch.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error.
        '''</summary>
        Friend ReadOnly Property jsd_error() As String
            Get
                Return ResourceManager.GetString("jsd_error", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Offline.
        '''</summary>
        Friend ReadOnly Property jsd_offline() As String
            Get
                Return ResourceManager.GetString("jsd_offline", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Out of Paper.
        '''</summary>
        Friend ReadOnly Property jsd_paperout() As String
            Get
                Return ResourceManager.GetString("jsd_paperout", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Paused.
        '''</summary>
        Friend ReadOnly Property jsd_paused() As String
            Get
                Return ResourceManager.GetString("jsd_paused", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Printed.
        '''</summary>
        Friend ReadOnly Property jsd_printed() As String
            Get
                Return ResourceManager.GetString("jsd_printed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Printing.
        '''</summary>
        Friend ReadOnly Property jsd_printing() As String
            Get
                Return ResourceManager.GetString("jsd_printing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Configuration File.
        '''</summary>
        Friend ReadOnly Property pd_ts_ConfigurationFile() As String
            Get
                Return ResourceManager.GetString("pd_ts_ConfigurationFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Data File.
        '''</summary>
        Friend ReadOnly Property pd_ts_DataFile() As String
            Get
                Return ResourceManager.GetString("pd_ts_DataFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Default Data Type.
        '''</summary>
        Friend ReadOnly Property pd_ts_DefaultDataType() As String
            Get
                Return ResourceManager.GetString("pd_ts_DefaultDataType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Driver DLL.
        '''</summary>
        Friend ReadOnly Property pd_ts_DriverPath() As String
            Get
                Return ResourceManager.GetString("pd_ts_DriverPath", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Environment.
        '''</summary>
        Friend ReadOnly Property pd_ts_Environment() As String
            Get
                Return ResourceManager.GetString("pd_ts_Environment", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Help File.
        '''</summary>
        Friend ReadOnly Property pd_ts_HelpFile() As String
            Get
                Return ResourceManager.GetString("pd_ts_HelpFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Monitor Name.
        '''</summary>
        Friend ReadOnly Property pd_ts_MonitorName() As String
            Get
                Return ResourceManager.GetString("pd_ts_MonitorName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Name.
        '''</summary>
        Friend ReadOnly Property pd_ts_Name() As String
            Get
                Return ResourceManager.GetString("pd_ts_Name", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Operating System Version.
        '''</summary>
        Friend ReadOnly Property pd_ts_OperatingSystemVersion() As String
            Get
                Return ResourceManager.GetString("pd_ts_OperatingSystemVersion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Print job redirection failed.
        '''</summary>
        Friend ReadOnly Property pem_JobTransferFailed() As String
            Get
                Return ResourceManager.GetString("pem_JobTransferFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Insufficient print job access rights.
        '''</summary>
        Friend ReadOnly Property pem_NoJobAccess() As String
            Get
                Return ResourceManager.GetString("pem_NoJobAccess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Insufficient rights to pause printing.
        '''</summary>
        Friend ReadOnly Property pem_NoPause() As String
            Get
                Return ResourceManager.GetString("pem_NoPause", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Insufficient access rights.
        '''</summary>
        Friend ReadOnly Property pem_NoPrinterAccess() As String
            Get
                Return ResourceManager.GetString("pem_NoPrinterAccess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Insufficient rights to resume printing.
        '''</summary>
        Friend ReadOnly Property pem_NoResume() As String
            Get
                Return ResourceManager.GetString("pem_NoResume", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Average Pages Per Month.
        '''</summary>
        Friend ReadOnly Property pi_ts_AveragePagesPerMonth() As String
            Get
                Return ResourceManager.GetString("pi_ts_AveragePagesPerMonth", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Comment.
        '''</summary>
        Friend ReadOnly Property pi_ts_Comment() As String
            Get
                Return ResourceManager.GetString("pi_ts_Comment", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Default Print Job Data Type.
        '''</summary>
        Friend ReadOnly Property pi_ts_DefaultDataType() As String
            Get
                Return ResourceManager.GetString("pi_ts_DefaultDataType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Driver Name.
        '''</summary>
        Friend ReadOnly Property pi_ts_DriverName() As String
            Get
                Return ResourceManager.GetString("pi_ts_DriverName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Default.
        '''</summary>
        Friend ReadOnly Property pi_ts_is_IsDefault() As String
            Get
                Return ResourceManager.GetString("pi_ts_is_IsDefault", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Network Printer.
        '''</summary>
        Friend ReadOnly Property pi_ts_is_IsNetworkPrinter() As String
            Get
                Return ResourceManager.GetString("pi_ts_is_IsNetworkPrinter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Shared.
        '''</summary>
        Friend ReadOnly Property pi_ts_is_IsShared() As String
            Get
                Return ResourceManager.GetString("pi_ts_is_IsShared", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Count of Queued Jobs.
        '''</summary>
        Friend ReadOnly Property pi_ts_JobCount() As String
            Get
                Return ResourceManager.GetString("pi_ts_JobCount", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Location.
        '''</summary>
        Friend ReadOnly Property pi_ts_Location() As String
            Get
                Return ResourceManager.GetString("pi_ts_Location", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Not Default.
        '''</summary>
        Friend ReadOnly Property pi_ts_not_IsDefault() As String
            Get
                Return ResourceManager.GetString("pi_ts_not_IsDefault", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Local Printer.
        '''</summary>
        Friend ReadOnly Property pi_ts_not_IsNetworkPrinter() As String
            Get
                Return ResourceManager.GetString("pi_ts_not_IsNetworkPrinter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Not Shared.
        '''</summary>
        Friend ReadOnly Property pi_ts_not_IsShared() As String
            Get
                Return ResourceManager.GetString("pi_ts_not_IsShared", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Parameters.
        '''</summary>
        Friend ReadOnly Property pi_ts_Parameters() As String
            Get
                Return ResourceManager.GetString("pi_ts_Parameters", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Port.
        '''</summary>
        Friend ReadOnly Property pi_ts_PortName() As String
            Get
                Return ResourceManager.GetString("pi_ts_PortName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Printer Name.
        '''</summary>
        Friend ReadOnly Property pi_ts_PrinterName() As String
            Get
                Return ResourceManager.GetString("pi_ts_PrinterName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Print Processor.
        '''</summary>
        Friend ReadOnly Property pi_ts_PrintProcessor() As String
            Get
                Return ResourceManager.GetString("pi_ts_PrintProcessor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Default Print Job Priority.
        '''</summary>
        Friend ReadOnly Property pi_ts_Priority() As String
            Get
                Return ResourceManager.GetString("pi_ts_Priority", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Job Seperator Filename.
        '''</summary>
        Friend ReadOnly Property pi_ts_SeperatorFilename() As String
            Get
                Return ResourceManager.GetString("pi_ts_SeperatorFilename", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Server Name.
        '''</summary>
        Friend ReadOnly Property pi_ts_ServerName() As String
            Get
                Return ResourceManager.GetString("pi_ts_ServerName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Shared As.
        '''</summary>
        Friend ReadOnly Property pi_ts_ShareName() As String
            Get
                Return ResourceManager.GetString("pi_ts_ShareName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Time Restriction.
        '''</summary>
        Friend ReadOnly Property pi_ts_TimeWindow() As String
            Get
                Return ResourceManager.GetString("pi_ts_TimeWindow", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Copies.
        '''</summary>
        Friend ReadOnly Property pj_ts_Copies() As String
            Get
                Return ResourceManager.GetString("pj_ts_Copies", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Data Type.
        '''</summary>
        Friend ReadOnly Property pj_ts_DataType() As String
            Get
                Return ResourceManager.GetString("pj_ts_DataType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Document.
        '''</summary>
        Friend ReadOnly Property pj_ts_Document() As String
            Get
                Return ResourceManager.GetString("pj_ts_Document", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Printer Driver.
        '''</summary>
        Friend ReadOnly Property pj_ts_Drivername() As String
            Get
                Return ResourceManager.GetString("pj_ts_Drivername", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Color.
        '''</summary>
        Friend ReadOnly Property pj_ts_is_Color() As String
            Get
                Return ResourceManager.GetString("pj_ts_is_Color", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Landscape.
        '''</summary>
        Friend ReadOnly Property pj_ts_is_Landscape() As String
            Get
                Return ResourceManager.GetString("pj_ts_is_Landscape", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Job Size (in Bytes).
        '''</summary>
        Friend ReadOnly Property pj_ts_JobSize() As String
            Get
                Return ResourceManager.GetString("pj_ts_JobSize", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Machine.
        '''</summary>
        Friend ReadOnly Property pj_ts_MachineName() As String
            Get
                Return ResourceManager.GetString("pj_ts_MachineName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Black and White.
        '''</summary>
        Friend ReadOnly Property pj_ts_not_Color() As String
            Get
                Return ResourceManager.GetString("pj_ts_not_Color", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Potrait.
        '''</summary>
        Friend ReadOnly Property pj_ts_not_Landscape() As String
            Get
                Return ResourceManager.GetString("pj_ts_not_Landscape", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Notify User.
        '''</summary>
        Friend ReadOnly Property pj_ts_NotifyUserName() As String
            Get
                Return ResourceManager.GetString("pj_ts_NotifyUserName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pages Printed.
        '''</summary>
        Friend ReadOnly Property pj_ts_PagesPrinted() As String
            Get
                Return ResourceManager.GetString("pj_ts_PagesPrinted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Paper Type.
        '''</summary>
        Friend ReadOnly Property pj_ts_PaperKind() As String
            Get
                Return ResourceManager.GetString("pj_ts_PaperKind", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Page Length.
        '''</summary>
        Friend ReadOnly Property pj_ts_PaperLength() As String
            Get
                Return ResourceManager.GetString("pj_ts_PaperLength", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Paper Source.
        '''</summary>
        Friend ReadOnly Property pj_ts_PaperSource() As String
            Get
                Return ResourceManager.GetString("pj_ts_PaperSource", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Page Width.
        '''</summary>
        Friend ReadOnly Property pj_ts_PaperWidth() As String
            Get
                Return ResourceManager.GetString("pj_ts_PaperWidth", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Parameters.
        '''</summary>
        Friend ReadOnly Property pj_ts_Parameters() As String
            Get
                Return ResourceManager.GetString("pj_ts_Parameters", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Position in Queue.
        '''</summary>
        Friend ReadOnly Property pj_ts_Position() As String
            Get
                Return ResourceManager.GetString("pj_ts_Position", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Printer.
        '''</summary>
        Friend ReadOnly Property pj_ts_PrinterName() As String
            Get
                Return ResourceManager.GetString("pj_ts_PrinterName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Resolution.
        '''</summary>
        Friend ReadOnly Property pj_ts_PrinterResolutionKind() As String
            Get
                Return ResourceManager.GetString("pj_ts_PrinterResolutionKind", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Horizontal Resolution.
        '''</summary>
        Friend ReadOnly Property pj_ts_PrinterResolutionX() As String
            Get
                Return ResourceManager.GetString("pj_ts_PrinterResolutionX", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Vertical Resolution.
        '''</summary>
        Friend ReadOnly Property pj_ts_PrinterResolutionY() As String
            Get
                Return ResourceManager.GetString("pj_ts_PrinterResolutionY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Print Processor.
        '''</summary>
        Friend ReadOnly Property pj_ts_PrintProcessorName() As String
            Get
                Return ResourceManager.GetString("pj_ts_PrintProcessorName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Priority.
        '''</summary>
        Friend ReadOnly Property pj_ts_Priority() As String
            Get
                Return ResourceManager.GetString("pj_ts_Priority", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Time in Queue.
        '''</summary>
        Friend ReadOnly Property pj_ts_QueuedTime() As String
            Get
                Return ResourceManager.GetString("pj_ts_QueuedTime", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Status.
        '''</summary>
        Friend ReadOnly Property pj_ts_StatusDescription() As String
            Get
                Return ResourceManager.GetString("pj_ts_StatusDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Submitted.
        '''</summary>
        Friend ReadOnly Property pj_ts_Submitted() As String
            Get
                Return ResourceManager.GetString("pj_ts_Submitted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Print Time Restriction.
        '''</summary>
        Friend ReadOnly Property pj_ts_TimeWindow() As String
            Get
                Return ResourceManager.GetString("pj_ts_TimeWindow", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Total Pages.
        '''</summary>
        Friend ReadOnly Property pj_ts_TotalPages() As String
            Get
                Return ResourceManager.GetString("pj_ts_TotalPages", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to User.
        '''</summary>
        Friend ReadOnly Property pj_ts_UserName() As String
            Get
                Return ResourceManager.GetString("pj_ts_UserName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cannot cancel print job.
        '''</summary>
        Friend ReadOnly Property pjerr_cancel() As String
            Get
                Return ResourceManager.GetString("pjerr_cancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cannot delete print job.
        '''</summary>
        Friend ReadOnly Property pjerr_delete() As String
            Get
                Return ResourceManager.GetString("pjerr_delete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cannot update print job.
        '''</summary>
        Friend ReadOnly Property pjerr_update() As String
            Get
                Return ResourceManager.GetString("pjerr_update", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to From.
        '''</summary>
        Friend ReadOnly Property tw_ts_From() As String
            Get
                Return ResourceManager.GetString("tw_ts_From", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unrestricted.
        '''</summary>
        Friend ReadOnly Property tw_ts_Unrestricted() As String
            Get
                Return ResourceManager.GetString("tw_ts_Unrestricted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Until.
        '''</summary>
        Friend ReadOnly Property tw_ts_Until() As String
            Get
                Return ResourceManager.GetString("tw_ts_Until", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
